server:
  port: 8080

security:
  jwt:
    secret: "clave-super-segura-de-minimo-32-caracteres-123456"
    expiration-millis: 3600000

spring:
  application:
    name: gafas-api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gafasdb
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
